Export output zip files seperately by ftp depending on configuration
farao-community/gridcapa-export pull request #4
Opened 2022-10-25 09:58 UTC by schwitzguebel

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-10-26 10:12 UTC, TheMaskedTurtle requested changes

2022-10-26 10:12 UTC, TheMaskedTurtle commented on src/main/java/com/farao_community/farao/gridcapa/export/GridcapaExportService.java
> +                        uploadZipToFtpFromResponseEntity(responseEntity);
You can rename the methods, it's quite confusing now, because the individual files won't be zipped anymore I think

2022-10-26 10:12 UTC, TheMaskedTurtle commented on src/test/java/com/farao_community/farao/gridcapa/export/GridcapaExportServiceTest.java
> +        ReflectionTestUtils.setField(outputsToFtpService, "seperateOutputFiles", true);
I didn't know that, usually we try to use test configuration that are loaded preferentially during tests, but that's quite tricky everytime. Thanks for the tip :)

2022-10-27 13:25 UTC, schwitzguebel commented on src/main/java/com/farao_community/farao/gridcapa/export/GridcapaExportService.java
> +                        uploadZipToFtpFromResponseEntity(responseEntity);
In fact the individual files aren't zipped by gridcapa-export, gridcapa-export never zipped anything, but gridcapa-task-manager zips the total output files byt hte other service call (default call). I will change name.

2022-10-27 13:36 UTC, schwitzguebel commented on src/test/java/com/farao_community/farao/gridcapa/export/GridcapaExportServiceTest.java
> +        ReflectionTestUtils.setField(outputsToFtpService, "seperateOutputFiles", true);
you can change values (even private values) by Java reflectionAPI, this is an easy way to do it with a Spring utils library: see : https://www.baeldung.com/java-call-private-method#java-reflection-api

2022-10-27 13:36 UTC, TheMaskedTurtle requested changes

2022-10-27 13:36 UTC, TheMaskedTurtle commented on src/main/java/com/farao_community/farao/gridcapa/export/GridcapaExportService.java
> +        String fileOutputName = getZipNameFromResponseEntity(responseEntity);
Can you change the name of this one as well ? It is still confusing

2022-10-27 13:37 UTC, schwitzguebel commented on src/main/java/com/farao_community/farao/gridcapa/export/GridcapaExportService.java
> +        String fileOutputName = getZipNameFromResponseEntity(responseEntity);
oops forgot sorry, missed that one

2022-10-27 14:03 UTC, TheMaskedTurtle approved these changes

2022-10-27 14:03 UTC, merged